package com.example.mygame.game.level

import androidx.compose.ui.graphics.Color

data class StorySceneTheme(
    val outerGradientColors: List<Color>,
    val skyGradientColors: List<Color>,
    val waterColor: Color,
    val groundTopColor: Color,
    val groundBottomColor: Color,
    val sunCoreColor: Color,
    val sunHaloEdgeColor: Color,
    val platformTopColor: Color,
    val platformBottomColor: Color,
    val brickColor: Color,
    val brickShadeColor: Color,
    val questionColor: Color,
    val questionUsedColor: Color,
    val questionMarkColor: Color,
    val sealBodyColor: Color,
    val sealBellyColor: Color,
    val birdWingColor: Color,
    val birdBodyColor: Color,
    val fishBodyColor: Color,
    val fishTailColor: Color,
    val hillSnowColor: Color,
    val hillStoneColor: Color,
    val hutWallColor: Color,
    val hutRoofColor: Color,
    val hutBeamColor: Color,
    val foregroundMistColor: Color,
    val foregroundShardColor: Color,
    val snowflakeAlphaBase: Float,
    val snowflakeAlphaStep: Float,
    val cloudCount: Int,
    val ridgeCount: Int,
    val hillCount: Int,
    val hutCount: Int,
)
